### ISSUE TITLE
attachement links unfunctional

### ISSUE THREAD

**Issue by tokeriis** [akosbalasko/yarle#163]
Having exported all my notes, it seems links to pdf's and other attachments has reversed link and descriptions.

Shouldn't
```

[[./_resources/typografiske___grafiske_udtryk.resources/Grafiskefagudtryk.pdf]]

```
be more like this?:
```

[[]](./_resources/typografiske___grafiske_udtryk.resources/Grafiskefagudtryk.pdf)

```

Also, I think attachment should be put in one folder for each enex file rather than separate sub folders for each note. Or at least an option for this would be nice.

**Comment by akosbalasko** [comment]
Hi @tokeriis !

[[ ]] brackets are generated because outputFormat is set to `ObsidianMD`. Please change it to `UrlEncodeMD`to have the standard md link format, which is []() . 

Thank you for the feedback, I'll copy your feat. request to another issue

**Comment by tokeriis** [comment]
the outputFormat was set to StandardMD, as in the documentation. Now I have changed to UrlEncodeMD. its different, but still not usable as a file link:

`[[./_resources/Bente_Kristiansen__Om_at_skrive_på_universitetet.resources/Om at skrive på universitetet kap 6 kopi.pdf | Om at skrive på universitetet kap 6 kopi.pdf]]`

I have also tried to completely remove the outputformat line from config.json, which creates another funky variation??

`[[./_resources/Bente_Kristiansen__Om_at_skrive_på_universitetet.resources/Om at skrive på universitetet kap 6 kopi.pdf]]
`

It should be:

`[Om at skrive på universitetet kap 6 kopi.pdf](./_resources/Bente_Kristiansen__Om_at_skrive_på_universitetet.resources/Om at skrive på universitetet kap 6 kopi.pdf) 
`

In addition I found another problem: Attached applescripts (with .scpt extension) has changed file extension to octet-stream, e.g in this case "safari_export_PDF.scpt" becomes this:

[[./_resources/Akademisk_workflow.resources/safari_export_PDF.1.octet-stream | safari\_export\_PDF.1.octet-stream]]

**Comment by akosbalasko** [comment]
Hi @tokeriis , I fixed the mentioned issues, please try again. 
Cheers,
akos

**Comment by tokeriis** [comment]
Still not there. 

`[[./_resources/Bente_Kristiansen__Om_at_skrive_på_universitetet.resources/Om at skrive på universitetet kap 6 kopi.pdf]]
`
I still can't click and open this link in any markdown editor.

and this:

`[[./_resources/Akademisk_workflow.resources/Gem læsbar PDF.zip]][[./_resources/Akademisk_workflow.resources/safari_export_PDF.1.bin]]`

.zip extension is renamed to a .bin extension.

**Comment by akosbalasko** [comment]
Ok, then please provide me an example enex file to be able to investigate the issues. Thank you.
