### ISSUE TITLE
Exported notes attachment does not link correctly in Obsidian

### ISSUE THREAD

**Issue by aashish108** [akosbalasko/yarle#246]
Hey there, I tried out your tool and none of the notes attachment is linking correctly in Obsidian. I see the attachment though. Internal links are using the Wikilinks style. 

Is this ticket related to https://github.com/akosbalasko/yarle/issues/242? Looks like if I get rid of the path it works which means the attachment needs a unique name to it perhaps?

Thanks

Edit:

The link contains backslashes when it should be forwardslashes on Windows, is there any reason for this or is this a bug?

```
[[.\_resources\201102152017_FFDSHOW_Settings_Guide_-_Beyond3D_Forum.resources/unknown_filename.1.gif]]
```

**Comment by akosbalasko** [comment]
Hi @aashish108 , no reason for this, I had a feeling that I eliminated all of these platform-dependent issues including this folder separators (on Linux it's / while on Windows it's \ ).
I'll check it out soon.

**Comment by akosbalasko** [comment]
@aashish108 , I released a new version (4.0.5) that resolved the problem you mentioned in the Edit section. Could you please retry it, to confirm that it works properly from now? 

Thanks in advance!

**Comment by aashish108** [comment]
I am getting this error, this make sense @akosbalasko ?

```
[Window Title]
Error

[Main Instruction]
A JavaScript error occurred in the main process

[Content]
Uncaught Exception:
Error: Image could not be created from C:\Users\Aashish\AppData\Local\yarle\app-4.0.5\resources\app\dist\ui\assets\icons\png\64x64.png
    at App.createWindow (C:\Users\Aashish\AppData\Local\yarle\app-4.0.5\resources\app\dist\ui\main.js:76:20)
    at App.emit (events.js:228:7)

[OK]
```

**Comment by akosbalasko** [comment]
Oh, okay, sorry @aashish108 , it's fixed in 4.0.6 sorry for the inconveniences.

**Comment by aashish108** [comment]
Thanks for that @akosbalasko . There is another issue though :O the paths are still wrong for the attachment links:

This does not work:
```
![[.\_resources\201103231232_Shark007's_FREE_Codec_solutions_-_Windows_7_codecs.resources\unknown_filename.1.jpeg]]
```

This does work:
```
![[./_resources/201103231232_Shark007's_FREE_Codec_solutions_-_Windows_7_codecs.resources/unknown_filename.1.jpeg]]
```

Basically, it's a forward slash that appears to work.

Thanks!

**Comment by akosbalasko** [comment]
Wow @aashish108 , thats becomes a strange issue, so in case of links Obsidian recognize / only. 
Well, good to know, I'll improve the the code in the upcoming days (probably tomorrow), and keep you updated. Thank you for your comments, they are really valuable for me to improve Yarle!

**Comment by akosbalasko** [comment]
Hi @aashish108 , the new version is released, it should produce the right path separators (/ only) independently from the OS.

**Comment by aashish108** [comment]
Hi @akosbalasko thanks for that! Did you forget to release the new version? I still see the old version up and it still has the same issue.

Cheers.

**Comment by akosbalasko** [comment]
Hi @aashish108 , nope, i missed to update you about i had to revert that release because the it did not work properly. Currently I'm working on the solution hoping that i'll be able to fix it within a couple of days.

**Comment by akosbalasko** [comment]
Hi @aashish108 , I have the fix released as 4.0.8, it should work now.

**Comment by aashish108** [comment]
Thanks @akosbalasko, it's all great.
