### ISSUE TITLE
Suffix for notes with same name does not increment

### ISSUE THREAD

**Issue by montemartin** [akosbalasko/yarle#363]
When several notes have the exact same name subsequent notes after the first get created with the same name.

I have a lot notes using the format `{company} - ${value}` for reciepts and invoices, so I end up with a lot of notes with similar contents, but identical names (i.e. "Github - $4.00"). When I process that notebook with Yarle the first note is created fine, and the second note is created as "Github - $4.00.1". 

But that `.1` suffix fails to increment so each note after that overwrites the previous note. The result is only the first and last note with a particular name are saved. It also looks like it processes perfectly, so it's difficult to find where the issue is.

**Comment by akosbalasko** [comment]
hi @montemartin ,

oops, that's really strange, i investigate it asap.

**Comment by akosbalasko** [comment]
@montemartin I found the bug, i'll release a fixed version soon.
Thank you for reporting this issue!

**Comment by montemartin** [comment]
Great! I'm happy to test it out once you have it fixed.

**Comment by akosbalasko** [comment]
Hi @montemartin ,
I released a new version for Mac and Linux (something fails on Windows around the dependency compilation, but I'm sure it is unrelated), so version 4.8.5 contains the fixes of both of the issues you raised. 
I'd close these issues, but feel free to reopen them if you think that something is still not correct.

**Comment by montemartin** [comment]
Thanks! I just ran a couple tests on some of my original exports. #362 is definitely fixed. The incrementing issue is still having some problems. 

Most of the notes with duplicated names are successfully incrementing now. However it seems to fail intermittently. I'm getting note names like 
- "Company 1 - $25"
- - "Company 1 - $25"
- - "Company 1 - $25"
- - "Company 1 - $25"
- - "Company 1 - $25"

**Comment by montemartin** [comment]
Thanks! I ran some quick trials on my notebooks. The issue with #362 is definitely fixed. However this incrementation problem is still not quite right. It's incrementing now, but seems to fail intermittently with some of the incremented notes missing. Now I have notes named as follows:

- "Company 1 - $25"
- "Company 1 - $25.1"
- "Company 1 - $25.2"
- "Company 1 - $25.4"
- "Company 1 - $25.6"
- "Company 1 - $25.7"
- "Company 2 - $99"
- "Company 2 - $99.1"
- "Company 2 - $99.3"

The missing number doesn't seem to follow any pattern.
