### ISSUE TITLE
example enex is missing from Yarle's bundle

### ISSUE THREAD

**Issue by klossgott** [akosbalasko/yarle#417]
See attached screengrab

![Capture](https://user-images.githubusercontent.com/4755429/200250350-673161af-b625-4b2a-9a41-02432bdcf767.PNG)

**Comment by akosbalasko** [comment]
Hi @klossgott ,
Thanks for this report, it looks like that the example enex file is missing from Yarle's bundle. So please select your enex file in the first step, and this error should be resolved.

**Comment by klossgott** [comment]
Hi there Akos,

Thanks so much for your response.

Unfortunately this does not fix the issue.  I have selected the file, this
time on a Mac, and still get the same error.

Here is the screenshot:
https://capture.dropbox.com/YQJWbgHLYKNMJgvF

Hope you can fix it!

Best wishes,

Ksi

**Comment by akosbalasko** [comment]
Hi @klossgott ,
Do you see the path to the selected enex file in Step 1? 
<img width="891" alt="Screenshot 2022-11-17 at 22 27 06" src="https://user-images.githubusercontent.com/11886731/202563634-2477f59e-2c67-4aef-b7bf-36d98df889ce.png">

**Comment by akosbalasko** [comment]
Hi @klossgott ,
I think a relevant fix has been released recently (5.0.7) which as I see solves an issue that looks the same as this one. 
I'd close this issue, but do not hesitate to reopen or create a new issue, if you still have problems. 
Thank you very much!
